package com.mycompany.prototipojframe;

import Entities.EAirplane;
import Entities.EFlight;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Principal extends javax.swing.JFrame {
    
    private ArrayList<EAirplane> airplanes;
    private ArrayList<EFlight> flights;
    
    public Principal() {
        airplanes = new ArrayList<EAirplane>();
        flights = new ArrayList<EFlight>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAvailable = new javax.swing.ButtonGroup();
        btnGroupStatus = new javax.swing.ButtonGroup();
        JPannel = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JTabbedPane();
        JPanelFlight = new javax.swing.JPanel();
        jLblOrigin = new javax.swing.JLabel();
        jLblDestiny = new javax.swing.JLabel();
        jLblExpDepartureTime = new javax.swing.JLabel();
        jLblDepartureTime = new javax.swing.JLabel();
        jLblExpArrivalTime = new javax.swing.JLabel();
        jLblArrivalTime = new javax.swing.JLabel();
        jLblAirline = new javax.swing.JLabel();
        jLblStatus = new javax.swing.JLabel();
        jTxtDestiny = new javax.swing.JTextField();
        jTxtExpDeparture = new javax.swing.JTextField();
        jTxtDeparture = new javax.swing.JTextField();
        jTxtExpArrival = new javax.swing.JTextField();
        jTxtArrival = new javax.swing.JTextField();
        jTxtAirline = new javax.swing.JTextField();
        jLblAirplane = new javax.swing.JLabel();
        jBtnAddFlight = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLblModel = new javax.swing.JLabel();
        jLblPassenger = new javax.swing.JLabel();
        jLblTank = new javax.swing.JLabel();
        jLblAvailable = new javax.swing.JLabel();
        jTxtModel = new javax.swing.JTextField();
        jTxtPassenger = new javax.swing.JTextField();
        jTxtTank = new javax.swing.JTextField();
        jBtnModify = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jTxtEmail = new javax.swing.JTextField();
        jBtnEmail = new javax.swing.JButton();
        jBtnImport = new javax.swing.JButton();
        jRbtnAvailable = new javax.swing.JRadioButton();
        jRbtnNonAvailable = new javax.swing.JRadioButton();
        jRbtnOnAir = new javax.swing.JRadioButton();
        jRbtnDelay = new javax.swing.JRadioButton();
        jRbtnLanded = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTxtOrigin = new javax.swing.JTextField();
        jPanelBinnacle = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyect Group9");

        JPanelFlight.setPreferredSize(new java.awt.Dimension(400, 360));

        jLblOrigin.setText("Origin:");

        jLblDestiny.setText("Destiny:");

        jLblExpDepartureTime.setText("Expected Departure Time:");

        jLblDepartureTime.setText("Departurer Time:");

        jLblExpArrivalTime.setText("Expected Arrival Time:");

        jLblArrivalTime.setText("Arrival Time: ");

        jLblAirline.setText("Airline:");

        jLblStatus.setText("Status:");

        jLblAirplane.setText("Airplane");

        jBtnAddFlight.setText("Add");
        jBtnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddFlightActionPerformed(evt);
            }
        });

        jLabel1.setText("Flights");

        jLblModel.setText("Model:");

        jLblPassenger.setText("Passenger Cap. :");

        jLblTank.setText("Tank Cap. :");

        jLblAvailable.setText("Available:");

        jBtnModify.setText("Modify");
        jBtnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModifyActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtnEmail.setText("Send Email");

        jBtnImport.setText("Import");

        btnGroupAvailable.add(jRbtnAvailable);
        jRbtnAvailable.setText("Available");

        btnGroupAvailable.add(jRbtnNonAvailable);
        jRbtnNonAvailable.setText("Non Available");

        btnGroupStatus.add(jRbtnOnAir);
        jRbtnOnAir.setText("On Air");

        btnGroupStatus.add(jRbtnDelay);
        jRbtnDelay.setText("Delay");

        btnGroupStatus.add(jRbtnLanded);
        jRbtnLanded.setText("Landed");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout JPanelFlightLayout = new javax.swing.GroupLayout(JPanelFlight);
        JPanelFlight.setLayout(JPanelFlightLayout);
        JPanelFlightLayout.setHorizontalGroup(
            JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(JPanelFlightLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBtnModify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnImport)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPanelFlightLayout.createSequentialGroup()
                        .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelFlightLayout.createSequentialGroup()
                                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblExpDepartureTime)
                                        .addComponent(jLblDepartureTime)
                                        .addComponent(jLblExpArrivalTime)
                                        .addComponent(jLblArrivalTime)
                                        .addComponent(jLblAirline)
                                        .addComponent(jLblStatus)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtExpArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtExpDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JPanelFlightLayout.createSequentialGroup()
                                        .addComponent(jRbtnOnAir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRbtnDelay)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRbtnLanded))))
                            .addGroup(JPanelFlightLayout.createSequentialGroup()
                                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblOrigin)
                                    .addComponent(jLblDestiny))
                                .addGap(121, 121, 121)
                                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtDestiny)
                                    .addComponent(jTxtOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelFlightLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanelFlightLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLblAirplane))
                                    .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelFlightLayout.createSequentialGroup()
                                            .addComponent(jLblAvailable)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                            .addComponent(jRbtnAvailable))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelFlightLayout.createSequentialGroup()
                                            .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLblPassenger)
                                                .addComponent(jLblTank)
                                                .addComponent(jLblModel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTxtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                                .addComponent(jTxtPassenger)
                                                .addComponent(jTxtTank))))))
                            .addGroup(JPanelFlightLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jBtnAddFlight)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jRbtnNonAvailable)))
                .addContainerGap())
        );
        JPanelFlightLayout.setVerticalGroup(
            JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLblAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblOrigin)
                    .addComponent(jLblModel)
                    .addComponent(jTxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDestiny)
                    .addComponent(jTxtDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPassenger)
                    .addComponent(jTxtPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblExpDepartureTime)
                    .addComponent(jTxtExpDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTank)
                    .addComponent(jTxtTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDepartureTime)
                    .addComponent(jTxtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAvailable)
                    .addComponent(jRbtnAvailable)
                    .addComponent(jRbtnNonAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblExpArrivalTime)
                    .addComponent(jTxtExpArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblArrivalTime)
                    .addComponent(jTxtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAirline)
                    .addComponent(jTxtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblStatus)
                    .addComponent(jBtnAddFlight)
                    .addComponent(jRbtnOnAir)
                    .addComponent(jRbtnDelay)
                    .addComponent(jRbtnLanded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(JPanelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnModify)
                    .addComponent(jBtnDelete)
                    .addComponent(jBtnEmail)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnImport))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelPrincipal.addTab("Flights", JPanelFlight);

        javax.swing.GroupLayout jPanelBinnacleLayout = new javax.swing.GroupLayout(jPanelBinnacle);
        jPanelBinnacle.setLayout(jPanelBinnacleLayout);
        jPanelBinnacleLayout.setHorizontalGroup(
            jPanelBinnacleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        jPanelBinnacleLayout.setVerticalGroup(
            jPanelBinnacleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jPanelPrincipal.addTab("Binnacle", jPanelBinnacle);

        javax.swing.GroupLayout JPannelLayout = new javax.swing.GroupLayout(JPannel);
        JPannel.setLayout(JPannelLayout);
        JPannelLayout.setHorizontalGroup(
            JPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal)
        );
        JPannelLayout.setVerticalGroup(
            JPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddFlightActionPerformed
        // TODO add your handling code here:
        addFlight();
    }//GEN-LAST:event_jBtnAddFlightActionPerformed

    private void jBtnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifyActionPerformed
        // TODO add your handling code here:
        modifyFlight();
    }//GEN-LAST:event_jBtnModifyActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        // TODO add your handling code here:
        deleteFlight();
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void addFlight(){
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE, MMM dd, yyyy HH:mm:ss a");
        
        boolean status;
        if(jRbtnAvailable.isSelected())
            status = true;
        else if(jRbtnNonAvailable.isSelected())
            status = false;
        
        char c;
        if(jRbtnDelay.isSelected())
            c='D';
        else if(jRbtnLanded.isSelected())
            c='L';
        else if(jRbtnOnAir.isSelected())
            c='O';
        
        
        airplanes.add(new EAirplane(
        
        ));
        
        flights.add(new EFlight(
               
        ));
        showFlight();
    }
    public void showFlight(){
             
    }
    public void deleteFlight(){
        int i = Integer.parseInt(JOptionPane.showInputDialog("Which record do you want to delete?"));
        i=i-1;
        flights.remove(i);
        airplanes.remove(i);
        showFlight();   
    }
    
    private void modifyFlight(){
        int i = Integer.parseInt(JOptionPane.showInputDialog("Which record do you want to modify?"));
        i=i-1;
        flights.set(i, new EFlight(/*argumentos*/));
        showFlight();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFlight;
    private javax.swing.JPanel JPannel;
    private javax.swing.ButtonGroup btnGroupAvailable;
    private javax.swing.ButtonGroup btnGroupStatus;
    private javax.swing.JButton jBtnAddFlight;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEmail;
    private javax.swing.JButton jBtnImport;
    private javax.swing.JButton jBtnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAirline;
    private javax.swing.JLabel jLblAirplane;
    private javax.swing.JLabel jLblArrivalTime;
    private javax.swing.JLabel jLblAvailable;
    private javax.swing.JLabel jLblDepartureTime;
    private javax.swing.JLabel jLblDestiny;
    private javax.swing.JLabel jLblExpArrivalTime;
    private javax.swing.JLabel jLblExpDepartureTime;
    private javax.swing.JLabel jLblModel;
    private javax.swing.JLabel jLblOrigin;
    private javax.swing.JLabel jLblPassenger;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTank;
    private javax.swing.JPanel jPanelBinnacle;
    private javax.swing.JTabbedPane jPanelPrincipal;
    private javax.swing.JRadioButton jRbtnAvailable;
    private javax.swing.JRadioButton jRbtnDelay;
    private javax.swing.JRadioButton jRbtnLanded;
    private javax.swing.JRadioButton jRbtnNonAvailable;
    private javax.swing.JRadioButton jRbtnOnAir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtAirline;
    private javax.swing.JTextField jTxtArrival;
    private javax.swing.JTextField jTxtDeparture;
    private javax.swing.JTextField jTxtDestiny;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtExpArrival;
    private javax.swing.JTextField jTxtExpDeparture;
    private javax.swing.JTextField jTxtModel;
    private javax.swing.JTextField jTxtOrigin;
    private javax.swing.JTextField jTxtPassenger;
    private javax.swing.JTextField jTxtTank;
    // End of variables declaration//GEN-END:variables
}
